name: Deploy Snipe-it Prod
on:
  push:
    branches:
      - main
   
   

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . --file Dockerfile      

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - name: deploy to prod
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd ~ && deploy.sh

